title: Your awesome title
language: "en"
baseurl: ""

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "default"

include: ["_pages"]

graph:
  pathColors:
    - /moc: "#aeaeae"

tooltip:
  contentQuerySelector: main
  tooltipLinksQuery: main a

wikilinks:
  tooltip:
    invalid_link: Article not found

nav:
  - label: Graph
    url: "graph"
  - label: Search ğŸ”
    url: "search"
